### ISSUE TITLE
[0007] Validação ddo formulário de Login

### ISSUE THREAD

**Issue by Ar3secchim** [Ar3secchim/project-77-days#15]
## 📊 Descrição 
 
Desenvolvimento de toda a parte de verificação de dados  e critérios de validações.

### 🛠️ Tasks a serem realizadas para a criação da PR
- [ ]  Decidir e justufucar a ultilização de libs (documentação)
- [ ] Escolha de lib
- [ ] Responsividade UI para feedbacks do usuário
